# Generated by Django 3.2.7 on 2021-09-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='verbose_name',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
